### ISSUE TITLE
[1.2.4d-12] Air pump is finnicky

### ISSUE THREAD

**Issue by thephoenixlodge** [joshiejack/Mariculture#242]
The Air Pump is a little weird about accepting power. In testing I have thus far found that it will not accept power from BC/RC/Forestry engines, or from kinesis pipes. 
From Mekanism, it will accept power straight from Power Cubes and from generators (wind turbines, solar etc), but will also not accept it from the unversal cables.

**Comment by joshiejack** [comment]
The air pump needs a constant supply of RF. Burst of RF won't work. The issue is those engines give RF in bursts rather than constantly. The Air Pump gives out air every 300 times it receives RF.

**Comment by thephoenixlodge** [comment]
That explains the engines, but not the pipes or universal cables, which I tested by directly hooking them up to transfer power from energy cubes

**Comment by joshiejack** [comment]
Not sure. But I'm too lazy to go and loook but I'd imagine it's the same principle with them not sending constantly (not sure how but eh). I'll just readd the sending air back in to onUpdate. Probably as a config option though >.<. Because it will be doing twice the work else... Well two config options :P. One for activating on receiving, and one for activating on tick :p.
