### ISSUE TITLE
Crash with NEI

### ISSUE THREAD

**Issue by quienti** [joshiejack/Mariculture#254]
http://pastebin.com/mDDxuKBZ

Mariculture : 1.2.4e
NEI : 1.0.4.83

**Comment by joshiejack** [comment]
For it to crash there. Something would have had to break NEI's item list. Or Something would have had to break my Crucible. This crash is not worth fixing. It would crash in other places anyways.

**Comment by SunshineHunter** [comment]
I get this crash too. But I don't think it's an issue with NEI or other mods, since everything is fine when I just delete Mariculture. And I already deleted EVERY mod in the folder once.

About the crash: Whenever I try to look up a recipe or the use of an block/item, it shows "Shutting down internal server..." and then this crash-report gets generated: http://pastebin.com/F8pinykn

Forge: 10.13.3.1428

CCC: 1.0.7.46 NEI: 1.0.5.110

Mariculture: 1.2.4.2a

I tried Forge 10.13.3.1420, with the same result.
