### ISSUE TITLE
fish feeder food count deleted when fish added

### ISSUE THREAD

**Issue by drunkangel** [joshiejack/Mariculture#258]
when you take a fish out of a fish feeder(or they die) and you put a new fish in, all of the food in the feeder is deleted. it seems that the refresh on the tank size on placing a new fish in does not keep track of the previous tank size or the food in the tank.

**Comment by joshiejack** [comment]
This is related to the fact that the male and female fish can have entirely waterblock requirements (lava vs water). So when the female or male is empty, it will try to reset the tank count and find that the water isn't valid because there is no male/female. I'll just make it leave the tank size alone if either the male or female aren't there. And only update when both are.
