### ISSUE TITLE
Compatiblity

### ISSUE THREAD

**Issue by zHawky** [joshiejack/Mariculture#259]
Hi! i like your mod, do yo think about some compatiblity between oceancraft, and maybe lycanites mobs?

**Comment by joshiejack** [comment]
This is very vague... You can't just make me read your brain and know what compatibility you want. What do you want.

**Comment by zHawky** [comment]
Well im asking wrong sorry, now im write abous small fixes;
Invar rods from AE2 Act like vanilla rod, i mean without bait,
then do you think about fish from Harvestcraft because your fish replace all type of fishes
and last, umm.. maybe fish breeding with Oceancraft fishes :D

**Comment by joshiejack** [comment]
I can't really add compatibility for other mods fishing rods from my end. I'd have to pretty much need to have a clone of theirs and replace their recipe. Or ASM in to their code. I could do that, but it's not worth it.

What about harvestcraft fish?

I have no desire to add other mods fish as breedable.

**Comment by zHawky** [comment]
Did you make compatiblity between biomes on RWG?

**Comment by Shyrocs** [comment]
Mariculture's armors models with Smart Moving mod, some Models always facing south
Hello,
Smart Moving,  is one of my favourite mods, and I like to try to get support for it when there are 3D Models that normally hook to the player, but since the player model is changed to allow, laying down, crawling, superman flying etc, it has a different hook than normal minecraft.
So I am not sure what exactly it would take to allow your models to hook to the player properly when using smart moving.
Tested with:
SmartCore-1.7.10-1.0.jar
SmartMoving-1.7.10-15.3.jar
SmartRender-1.7.10-2.1.jar
PlayerAPI-1.7.10-1.2.jar
RenderPlayerAPI-1.7.10-1.3.jar
+
Mariculture-Deluxe-1.7.10-1.2.4.1.jar
Enchiridion-1.7.X-1.2b.jar

I had the same problem with SimplyJetPacks, they have an issue topic on this page: https://github.com/Tonius/SimplyJetpacks/issues/84
With mods like TLCSpecialArmors and Flans mod I had no problems.

Thanks and congratulations for the mod.

**Comment by joshiejack** [comment]
Since I do not use smart moving myself. I have no interest in spending my time on it. If someone else wants to, that's fine. But I'm not adding support for a mod, I will never use.

**Comment by Shyrocs** [comment]
I apologise for bringing this issue up again but about Smart Moving compatibility, a while back I had a chat with Divisor about Smart moving and 3d rendering objects that stick to the player. I asked him why the armor, or other mods do not move when the player does, and this is a quote from him:

These issues with armor facing south have already been addressed. The compatibility has to be done by the other mod author although somewhere in this post Divisor has explained the means of doing so.
The mod author need to fix the compatibility with Player API, Render Player API and Smart Moving, adapting your mod.

This is a Divisor instruction for Render Player api, wich also works without Render Player Api:

" To solve this specific problem you need your mod's armor model class inherit from "api.player.model.ModelPlayer" instead of"net.minecraft.client.model.ModelBiped".

In case you want your mod to also work without Render Player API, you are going to need two identical armor model classes:

•	one inheriting from "net.minecraft.client.model.ModelBiped" and
•	the other one inheriting from "api.player.model.ModelPlayer".

Then create an instance of one of them depending on whether Render Player API is present or not.
