### ISSUE TITLE
Gammabright Issue

### ISSUE THREAD

**Issue by recklessrider** [joshiejack/Mariculture#278]
I'm having a random issue between Mariculture builds 1.2.4.1, 1.2.4.1a, 1.2.4.2 and 1.2.4.2a and Gammabright. If you have Gammabright activated and open an inventory or change dimensions it will deactivate Gammabright. This seems like a small issue but it gets pretty annoying having to reactivate it every time I need to check an inventory. Issue doesn't seem to occur on Mariculture version 1.2.4f and below.

**Comment by joshiejack** [comment]
It would have started occuring then, because I fixed a bug where brightness being set underwater by my scuba mask was broken. It probably has to do with the way gammabright handles it.

I cache the old brightness set when a player enters water. Then set their brightness really high, like gammabright. Then I set it back to whatever the cached value was, if their brightness is greater than what you can achieve normally. If gammabright is changing the normal minecraft setting it should behave fine. But anyways, it's not something I'm concerned about, since I'd consider gammabright a kinda cheating thing. If you don't ever use the scuba gear, I'd suggest you turn off the diving module. Then it will stop resetting the brightness.

**Comment by recklessrider** [comment]
Cool, thanks for the reply.

-Jason
