### ISSUE TITLE
Server's generates.

### ISSUE THREAD

**Issue by UUUii** [joshiejack/Mariculture#306]
Hi joshiejack, I found that limestone couldn't be generated at the bottom of the sea in my server:3

**Comment by joshiejack** [comment]
What other world generating mods do you have. In 1.3 I tried to change it so that my limestone generation would automatically be compatible with other dimensions without having to use my config >.>. But I guess if something is replacing the chunk provider for the overworld, it may break the generation.

**Comment by UUUii** [comment]
I just only put ench2 and Mariculture into my mods file, limestone still not be generated normally. I think errors were occurred at #17 in first, #17 also made processing’s and diving‘s book lose its localization. And also, when #17 coming, my partner said that limestone couldn't be generated at the bottom of the sea in his server although at that time I didn't care.

**Comment by UUUii** [comment]
Oh, #17 means Mariculture-Deluxe-1.7.10-1.3.0-17 XD

**Comment by joshiejack** [comment]
The books didn't lose their localisation they were rewritten entirely, the others are being worked on too. Switching from ench1 books to ench2 ones, and updating the docs. I'll investigate the limestone, I know it works in ssp for me, maybe messed something up for servers.

**Comment by UUUii** [comment]
Thanks a lot:3
